/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}", "./app/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "eco-dark": "#0f172a",
        "eco-card": "#1e293b",
        "eco-border": "#334155",
        "eco-green": "#10b981",
        "eco-green-glow": "#34d399",
        "eco-accent": "#0ea5e9",
        "status-danger": "#ef4444",
        "status-warning": "#f59e0b",
        // Neutral mode colors
        "neutral-bg": "#374151",
        "neutral-card": "#4b5563",
        "neutral-border": "#6b7280",
        "neutral-text": "#f3f4f6",
        // System theme colors (Environmental Dark)
        "system-bg": "#0F1B11",
        "system-card": "#1A2E1F",
        "system-text": "#E1E4E1",
        "system-border": "rgba(123, 160, 91, 0.2)",
        "system-accent": "#7BA05B",

        // New Material Theme Colors
        "on-tertiary": "#fff1db",
        "surface-container-low": "#bbffe3",
        "on-primary-container": "#005a3c",
        "surface-container-high": "#9ff3d3",
        "outline": "#45826c",
        "surface-dim": "#85e7c3",
        "secondary-fixed": "#68fcbf",
        "inverse-on-surface": "#6ca991",
        "on-tertiary-container": "#563e00",
        "surface-container": "#abf8d9",
        "tertiary-dim": "#674b00",
        "primary-fixed": "#69f6b8",
        "background": "#d9ffed",
        "error-dim": "#9f0519",
        "primary-container": "#69f6b8",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#004931",
        "primary": "#006947",
        "error-container": "#fb5151",
        "on-primary-fixed": "#00452d",
        "tertiary-fixed-dim": "#edb210",
        "on-tertiary-fixed-variant": "#614700",
        "inverse-primary": "#69f6b8",
        "secondary-fixed-dim": "#57edb1",
        "secondary": "#006948",
        "error": "#b31b25",
        "on-primary-fixed-variant": "#006544",
        "primary-dim": "#005c3d",
        "surface-container-highest": "#94eecc",
        "on-error-container": "#570008",
        "surface-bright": "#d9ffed",
        "tertiary": "#755600",
        "on-error": "#ffefee",
        "on-surface": "#003628",
        "on-secondary": "#c8ffe1",
        "surface-tint": "#006947",
        "on-secondary-fixed-variant": "#006948",
        "on-primary": "#c8ffe0",
        "secondary-dim": "#005b3f",
        "on-tertiary-fixed": "#3d2b00",
        "outline-variant": "#7cbaa1",
        "on-surface-variant": "#286652",
        "surface-variant": "#94eecc",
        "tertiary-container": "#fcc025",
        "tertiary-fixed": "#fcc025",
        "primary-fixed-dim": "#58e7ab",
        "on-secondary-container": "#005e40",
        "on-background": "#003628",
        "surface": "#d9ffed",
        "secondary-container": "#68fcbf",
        "inverse-surface": "#00120b"
      },

      fontFamily: {
        "headline": ["Fredoka"],
        "body": ["Quicksand"],
        "label": ["Quicksand"],
        "sans": ["Quicksand"],
        "mono": ["Space Mono"]
      },
      boxShadow: {
        glow: "0 0 10px rgba(16, 185, 129, 0.5)",
        "system-glow": "0 0 10px rgba(123, 160, 91, 0.5)",
      },
    },
  },
  plugins: [
    // Custom plugin for system: variant
    function ({ addVariant }) {
      addVariant("system", ".system &");
    },
  ],
};
