"""added new updated tables

Revision ID: 23e8cc3dfe87
Revises: b7f18def0e15
Create Date: 2026-01-08 14:36:21.720347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e8cc3dfe87'
down_revision = 'b7f18def0e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('partner_type', sa.String(length=50), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rvms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_uuid', sa.String(length=100), nullable=True),
    sa.Column('location_name', sa.String(length=100), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('total_items_collected', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_uuid')
    )
    op.create_table('recycling_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rvm_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_points_earned', sa.Integer(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['rvm_id'], ['rvms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recycling_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('weight_grams', sa.Float(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('deposited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['recycling_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward_redemptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed_by_partner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verification_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'transactions', ['transaction_id'], ['id'])
        batch_op.create_foreign_key(None, 'partners', ['claimed_by_partner_id'], ['id'])

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'partners', ['partner_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ['public_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('public_id')
        batch_op.drop_column('role')

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('partner_id')

    with op.batch_alter_table('reward_redemptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verification_notes')
        batch_op.drop_column('claimed_by_partner_id')

    op.drop_table('recycling_items')
    op.drop_table('recycling_sessions')
    op.drop_table('rvms')
    op.drop_table('partners')
    # ### end Alembic commands ###
