"""add reward_organization_assignments

Revision ID: 28f573608da0
Revises: b4bd76ae3539
Create Date: 2026-06-16 18:43:42.447473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f573608da0'
down_revision = 'b4bd76ae3539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_organization_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reward_id', 'organization_id', name='uq_reward_org')
    )
    with op.batch_alter_table('reward_organization_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_organization_assignments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_organization_assignments_reward_id'), ['reward_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward_organization_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_organization_assignments_reward_id'))
        batch_op.drop_index(batch_op.f('ix_reward_organization_assignments_organization_id'))

    op.drop_table('reward_organization_assignments')
    # ### end Alembic commands ###
