"""Add token_blacklist, city unique, credential index

Revision ID: 406e48d40e9e
Revises: edab494b5c67
Create Date: 2026-03-15 00:16:49.940345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406e48d40e9e'
down_revision = 'edab494b5c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blacklist_jti'), ['jti'], unique=True)

    with op.batch_alter_table('access_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_credentials_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_cities_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cities_name', type_='unique')

    with op.batch_alter_table('access_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_credentials_account_id'))

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_jti'))

    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
