"""added qr table for scanning

Revision ID: 7a359a1df547
Revises: b11e9f6af52f
Create Date: 2025-12-27 10:35:07.095861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a359a1df547'
down_revision = 'b11e9f6af52f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_data', sa.String(length=500), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=True),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_balance', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('points_balance')

    op.drop_table('qr_scans')
    # ### end Alembic commands ###
