"""empty message

Revision ID: b4bd76ae3539
Revises: rpi_auth
Create Date: 2026-06-05 01:24:59.493326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bd76ae3539'
down_revision = 'rpi_auth'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_categories_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rewards_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key(None, 'reward_categories', ['category_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('educational_level', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('year_level', sa.String(length=30), nullable=True))
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('year_level')
        batch_op.drop_column('educational_level')

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_rewards_category_id'))
        batch_op.drop_column('category_id')

    with op.batch_alter_table('reward_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_categories_organization_id'))

    op.drop_table('reward_categories')
    # ### end Alembic commands ###
